name: waryaa

on: [push]

jobs:
  run_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start
